export var Constants = {
	DEFAULT_DELAY: 2000,
	NODE_A: "NODE_A",
	NODE_B: "NODE_B",
	NODE_C: "NODE_C",
	CLIENT_NODE: "CLIENT_NODE",
	ANIMATION_STATE_INITIAL: 'ANIMATION_STATE_INITIAL',
	ANIMATION_STATE_FINISHED: "ANIMATION_STATE_FINISHED",
	COMMITTED: "(committed)",
	UNCOMMITTED: "(uncommitted)",
}
